### ISSUE TITLE
Turtle serialization of boolean values should have extra whitespace - can lead to parsing errors

### ISSUE THREAD

**Issue by joepio** [ruby-rdf/rdf-turtle#20]
When serialising a boolean with Turtle, there is no spacebar behind the boolean. This can (sometimes) lead to parsing errors. At least, we had [issues when parsing this](https://github.com/easyrdf/easyrdf/issues/393) with the PHP library [easy RDF](https://github.com/easyrdf/easyrdf). It's not entirely clear whether it is required to have a spacebar behind a boolean value from [the spec](https://www.w3.org/TR/turtle/), but in all examples, there is a whitespace.

How rdf-turtle serialises (no space behind boolean)

```turtle
<http://somecountry.example/census2007> <http://example.org/stats/islandlocked>  false.
```

What most will expect (one whitespace behind boolean)

```turtle
<http://somecountry.example/census2007> <http://example.org/stats/islandlocked>  false .
```

**Comment by gkellogg** [comment]
While the EBNF grammar typically does not require _any_ white space, the rdf-turtle writer pretty much always writes it when serializing, IIRC. Do you have a test class you can provide that demonstrates the behavior? A white space is typically _not_ used when writing a “,” or “;”, but is before “.” as a matter of my particular style. In the wild, both behaviors are common.

**Comment by gkellogg** [comment]
Looking more at the example you referenced, the processing problem with easyRdf seems to be with `true;`, not `true.`. Both are perfectly legal, and a parser would typically tokenize the input stream, and recognize `true` as a token, thus not need whitespace to separate these lexical elements.

This gem does, indeed, output statements such as `<> dc:title true; dx:offer "foo" .` (although using `true` for the value of dc:title is suspect), and other serializers will do the same thing. So, I suggest that the issue lies with easyRdf.
